Feature toggles
SAP/luigi pull request #1571
Opened 2020-08-17 15:03 UTC by JohannesDoberer

2020-08-18 11:03 UTC, alexandra-simeonova commented on docs/advanced-scenarios.md
> +```
`````suggestion

#### Usage

* To **set** feature toggles, you have two possibilities:

  1. Set feature toggles to the active feature toggle list through [Luigi Core API](luigi-core-api.md#featuretoggles):
  ```javascript
  Luigi.featureToggles().setFeatureToggle('ft1');
  ```

  2. Set feature toggles to the active feature toggle list via URL parameters:
  ```
  http://localhost:4200/projects/pr1?ft=ft1,ft2
  ```

* To **unset** feature toggles, you have to use the Core API:

  ```javascript
    Luigi.featureToggles().unsetFeatureToggle('ft1');
  ```

* To **restrict node visiblity with feature toggles**:

  You can define a list of feature toggles for a particular top or left navigation node. Then, you can use the [visibleForFeatureToggles](navigation-parameters-reference.md#visibleForFeatureToggles) parameter in order to display the node for certain feature toggles.
  For example, this node will be visible if `ft1` is added to the active feature toggle list:

  ```javascript
  {
      category: { label: 'Feature Toggle: Settings 2', icon: 'action-settings' },
      pathSegment: 'settings_ft',
      label: 'Project Settings 2',
      viewUrl: '/sampleapp.html#/projects/' + projectId + '/settings',
      icon: 'settings',
      visibleForFeatureToggles: ['ft1']
  }
  ```

  It is also possible to negate the visibility of a node by adding an exclamation mark at the beginning of the feature toggle name.
  In this example, the node will not be visible if `ft1` is set as an active feature toggle, but if another feature toggle like `ft2` is active, the node will be displayed:
  ```javascript
  {
      category: { label: 'Feature Toggle: Settings 2', icon: 'action-settings' },
      pathSegment: 'settings_ft',
      label: 'Project Settings 2',
      viewUrl: '/sampleapp.html#/projects/' + projectId + '/settings',
      icon: 'settings',
      visibleForFeatureToggles: ['!ft1']
  }
  ```

* To **use feature toggles in a micro frontend**:

  It is possible to restrict content in a micro frontend using feature toggles. The active feature toggle list is available in the Luigi [Client API](luigi-client-api.md#getActiveFeatureToggles).
  ```javascript
    if (LuigiClient.getActiveFeatureToggles().includes('ft1')) {
      //display content
    }
  ```
`````

2020-08-18 11:04 UTC, alexandra-simeonova commented on docs/advanced-scenarios.md
> +  Luigi.featureToggles().setFeatureToggle('ft1');
I assume it should be **unsetFeatureToggle** here instead, so I changed it in my suggestion (let me know if it's ok)

2020-08-18 11:08 UTC, alexandra-simeonova commented on docs/navigation-parameters-reference.md
> +- **description**: defines a list of feature toggles valid for this node. This list will be compared against the active feature toggles list. If there is a match the node will be visible in the left
```suggestion
- **description**: defines a list of feature toggles valid for this node. This list will be compared against the active feature toggles list. If there is a match, the node will be visible in the left navigation. It is also possible to negate the feature toggle by adding a `!` in front of the toggle name.  Then, the node will be visible for all other feature toggles except the one defined with an exclamation point.
```

2020-08-20 06:30 UTC, ndricimrr commented on docs/advanced-scenarios.md
> +Displaying nodes restricted to feature toggles in the top or left navigation you can define a list of feature toggles on the node.
- This sentence seems like it belongs beneath the title below: _#### Visibility of a node restricted by feature toggles_ .  Over here seems like it belongs to _“unset feature toggles..."_ right above. 

- Somethings a bit off with the sentence. How about sth like: **_In order to add node restrictions through feature toggles to the top or left navigation nodes you can define a list of feature toggles on the node_** , probably @alexandra-simeonova  can come up with sth better

2020-08-20 06:30 UTC, ndricimrr commented on docs/advanced-scenarios.md
> +If there is a feature toggle `ft1` added to the active feature toggle list, the node will be displayed when [visibleForFeatureToggles](navigation-parameters-reference.md#visibleForFeatureToggles) is
```suggestion
If there is a feature toggle `ft1` added to the active feature toggle list, the node will be displayed when [visibleForFeatureToggles](navigation-parameters-reference.md#visibleForFeatureToggles) is defined and also contains `ft1` as well.
```

2020-08-20 06:30 UTC, ndricimrr commented on test/e2e-test-application/src/app/project/project.component.html
> +              (click)="linkManager().navigate('/projects/pr1/settings?ft=test')"
This worked very well, just that after navigation finished you don't really notice what happens unless you query `getActiveFeatureToggleList`. Was thinking to add one more line to print/show a text if `ft=test` on the settings page as well, just like you do for ft1 🤔

2020-08-20 06:30 UTC, ndricimrr commented on test/e2e-test-application/src/app/project/project.component.html
> +                  .navigate('settings_ft?ft=test')
I got an error when clicking on this node:

![Screenshot 2020-08-20 at 08 21 43](https://user-images.githubusercontent.com/18335489/90724076-363f4080-e2be-11ea-97dc-892b419a4daf.png)

2020-08-20 07:21 UTC, JohannesDoberer commented on core/src/services/routing.js
> +          'featureToggles.queryStringParam is not defined in settings.js'
true.. good point

2020-08-24 08:42 UTC, maxmarkus commented on core/src/App.html
> +      }
works, imho harder to read as the original solution.

2020-08-24 14:52 UTC, maxmarkus requested changes
Good job, just some remarks.

2020-08-24 14:52 UTC, maxmarkus commented on core/src/core-api/featuretoggles.js
> +        console.log('Feature toggle name is not in the list.');
```suggestion
        console.warn('Feature toggle name is not in the list.');
```

2020-08-24 14:52 UTC, maxmarkus commented on core/src/core-api/featuretoggles.js
> +      console.log('Feature toggle name is empty or not a type of string');
```suggestion
      console.warn('Feature toggle name is empty or not a type of string');
```
I think we should avoid using classical logs, but use more meaningful console functions.

2020-08-24 14:52 UTC, maxmarkus commented on core/src/core-api/featuretoggles.js
> +        console.log('Feature toggle name already exists');
```suggestion
        console.warn('Feature toggle name already exists');
```

2020-08-24 14:52 UTC, maxmarkus commented on core/src/core-api/featuretoggles.js
> +      console.log('Feature toggle name is empty or not a type of string');
```suggestion
      console.warn('Feature toggle name is empty or not a type of string');
```

2020-08-24 14:52 UTC, maxmarkus commented on test/e2e-test-application/src/app/project/settings/settings.component.html
> +  class="fd-section luigi_featuretoggle_ft1"
Is the class _luigi_featuretoggle_ft1_ used somehow? Couldn't find a reference.

2020-08-24 14:52 UTC, maxmarkus commented on website/docs/src/luigi-config/extended/routing.js
> +  useHashRouting = true;
The docs should run with path routing?
```suggestion
  useHashRouting = false;
```

2020-08-24 14:52 UTC, maxmarkus commented on core/src/core-api/featuretoggles.js
> +    return get(this.featureToggleList);
Would be awesome to avoid possible mutations by returning a clone instead of reference.

2020-08-25 11:17 UTC, maxmarkus approved these changes
LGTM 👍

2020-08-25 17:19 UTC, merged