Luigi 1.5 release notes
SAP/luigi pull request #1678
Opened 2020-10-28 17:08 UTC by alexandra-simeonova

**Description**

Changes proposed in this pull request:

- Add Luigi 1.5 release notes

**Related issue(s)**

2020-10-28 18:46 UTC, hardl requested changes

2020-10-28 18:46 UTC, hardl commented on blog/2020-10-28-release-notes.md
> +This new feature allows a category in Luigi navigation to act as an accordion - when the user clicks another category the previously collapsed category is closed and the new one is opened. This featu
'the previously collapsed category is closed and the new one is opened ' - hmm, sounds wrong...
new proposal: 'the previously expanded category is collapsed and the new one is expanded'

2020-10-29 08:09 UTC, hardl approved these changes

2020-10-29 08:24 UTC, JohannesDoberer approved these changes

2020-10-29 10:13 UTC, merged