Fixing cypress tests for Angular Test Application
SAP/luigi pull request #1730
Opened 2020-11-25 11:43 UTC by legteodav

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**
fixes #1696

2020-12-02 10:38 UTC, UlianaMunich requested changes
Tests working like a charm locally, just a tiny cleanup left

2020-12-02 10:38 UTC, UlianaMunich commented on test/e2e-test-application/src/luigi-config/extended/helpers.js
> +      console.log('Inside projectsNavProviderFn --> ', result);
clean up :)

2020-12-02 10:38 UTC, UlianaMunich commented on test/e2e-test-application/src/luigi-config/extended/navigation.js
> +    console.log('getProductSwitcherItems allProjects =>', getAllProjectsSync());
clean up :)

2020-12-03 09:37 UTC, UlianaMunich approved these changes

2020-12-10 14:58 UTC, ndricimrr approved these changes
👍

2020-12-15 11:36 UTC, merged