Provide a e2e test for "withoutSync()" bug fix
SAP/luigi pull request #1744
Opened 2020-12-01 10:13 UTC by legteodav

Provide a e2e test for "withoutSync()" bug fix

**Related issue(s)**
Fixes #1733

2020-12-10 15:44 UTC, ndricimrr commented on test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
> +        // linkManager().withoutSync().navigate('/projects/pr2/virtual-tree')
```suggestion
        // CLICK ON navigate-withoutSync-settings
        // linkManager().withoutSync().navigate('/projects/pr2/settings')
```

2020-12-10 15:51 UTC, ndricimrr commented on test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
> +
```suggestion

```

2020-12-10 15:52 UTC, ndricimrr commented on test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
> +
```suggestion
```

2020-12-10 15:55 UTC, ndricimrr requested changes

2020-12-10 15:55 UTC, ndricimrr commented on test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
>  });
```suggestion
  });
});
```

2020-12-10 15:55 UTC, ndricimrr commented on test/e2e-test-application/e2e/tests/1-angular/navigation.spec.js
> +        // linkManager().withoutSync().navigate('/projects/pr2/virtual-tree')
```suggestion
        // CLICK ON navigate-withSync-virtual-tree
        // linkManager().navigate('/projects/pr2/virtual-tree')
```

2020-12-10 15:57 UTC, ndricimrr approved these changes
LGTM 👍

2020-12-14 07:53 UTC, JohannesDoberer commented
Waiting until #1760 is done.

2021-01-25 11:20 UTC, JohannesDoberer approved these changes

2021-01-27 14:53 UTC, merged