1800: Missing theming settings documentation
SAP/luigi pull request #1803
Opened 2021-01-08 16:03 UTC by legteodav

`Fixes #1800`

2021-01-12 08:29 UTC, JohannesDoberer approved these changes

2021-01-12 13:38 UTC, UlianaMunich commented on docs/general-settings.md
> +    * **nodeViewURLDecorator** (Optional) you can add an internal Luigi View Url decorator (below an example). Object is to add a query parameter where we add the current theme used by the applicatio
```suggestion
* **theming** is a configuration element that allows you to specify a list of themes that are available on the website. The children elements are mandatory:
    * **themes**  is an array of available themes, for example `themes: ['light', 'dark']`. 
    * **defaultTheme**  the default theme used by the application.
    * **nodeViewURLDecorator** (Optional) you can add an internal Luigi View Url decorator (an example is below). This object adds a query parameter where you can add a current theme used by the application when micro-frontends are loaded.
```

2021-01-12 13:55 UTC, UlianaMunich requested changes
Please see my suggestions

2021-01-13 15:03 UTC, UlianaMunich approved these changes
LGTM!

2021-01-19 09:27 UTC, alexandra-simeonova approved these changes

2021-01-21 14:57 UTC, merged