Support types for confirmation modal
SAP/luigi pull request #1863
Opened 2021-02-03 13:30 UTC by stanleychh

**Description**

- Support types for confirmation modal
- Replace css class from `fd-dialog` to `fd-message-box`
- Semantic types: `confirmation`, `success`, `error`, `warning`, `information`
https://sap.github.io/fundamental-styles/?path=/docs/components-message-box--structure

Fixes #1850

2021-02-08 10:18 UTC, UlianaMunich requested changes
A couple of additional suggestions from my side:
- we need to keep the previous version of the confirmation modal to support our non-sap related customers (the one which doesn't have an icon in the dialog header). I mean we still can use the confirmation modal but without the question mark. Means icon might be optional same as buttonConfirm.
- depending on the type of dialog box there might be 2 buttons OR one button in the footer  (error, success, warning, information has only one button)
- I think it makes sense to add all types of the confirmation modal we support into the documentation. Currently, only confirmation is listed
- could you please add some test to test 1 button in the footer, if possible?

2021-02-09 10:41 UTC, UlianaMunich approved these changes
Great job!

2021-02-09 10:45 UTC, alexandra-simeonova commented on client/src/uxManager.js
> +   * @param {string|false} [settings.buttonConfirm="Yes"] the label for the modal confirm button. Set false for not showing confirmation button.
```suggestion
   * @param {string|false} [settings.buttonConfirm="Yes"] the label for the modal confirmation button. If set to `false`, the button will not be shown.
```

2021-02-09 12:17 UTC, JohannesDoberer requested changes
Looks good 👍 .
One additional thing. We should change also documentation for core api in ux.js and the corresponding core docu as well.

2021-02-09 14:27 UTC, alexandra-simeonova approved these changes
Nice work!

2021-02-09 15:07 UTC, JohannesDoberer approved these changes
👍  LGTM!!!

2021-02-11 13:16 UTC, merged