1777 styles user settings dialog
SAP/luigi pull request #1884
Opened 2021-02-10 16:50 UTC by UlianaMunich

Fixes #1777

2021-02-11 07:24 UTC, legteodav commented on core/src/UserSettingsDialog.html
> +    console.log('resize');
```suggestion
```

2021-02-15 19:00 UTC, JohannesDoberer reviewed
![Bildschirmfoto 2021-02-15 um 19 58 09](https://user-images.githubusercontent.com/14272184/107984485-4fece680-6fc8-11eb-8048-3cb0a5020864.png)
I guess it was not introduced in this pr but it would be nice to fix it here

2021-02-15 19:09 UTC, JohannesDoberer commented
![File](https://user-images.githubusercontent.com/14272184/107985021-8e36d580-6fc9-11eb-8879-aeeb8ecc34b2.jpg)
If I have a longer list on custom Mf I can't see the last entry on mobile view.

2021-02-15 19:18 UTC, JohannesDoberer commented
![Filemobile](https://user-images.githubusercontent.com/14272184/107985685-d3a7d280-6fca-11eb-9d69-2225968a42eb.jpg)
If I have a longer list of entries in luigi editor I will not see the last element when I scroll to the end.

2021-02-15 19:32 UTC, JohannesDoberer commented
![Bildschirmfoto 2021-02-15 um 20 31 01](https://user-images.githubusercontent.com/14272184/107986633-c4c21f80-6fcc-11eb-8da1-ed0aa951a24b.png)
On standard view I would say the distance between content and footer is probably to high.

2021-02-17 13:24 UTC, JohannesDoberer commented on core/src/UserSettingsDialog.html
> +      overflow: auto;
When I remove the `overflow:auto` I don't get a double scrollbar on iframe mf.
Currently I have it? Does it make sense?

2021-02-17 13:26 UTC, JohannesDoberer commented on core/src/UserSettingsDialog.html
> +        overflow: auto;
I have a double scrollbar on iframe mf.
When I remove this `overflow:auto`, I don't have it.
Does it make sense? Can't see any side-effect.

2021-02-17 14:28 UTC, legteodav approved these changes

2021-02-17 20:44 UTC, JohannesDoberer commented
![IMG_7169](https://user-images.githubusercontent.com/14272184/108265418-07b8fa00-7169-11eb-8b2a-c175d6dad653.jpeg)
One small thing.. if I have a more entries in the nav I can't see the whole Item.

2021-02-19 17:10 UTC, JohannesDoberer requested changes
Please take a look to my suggestions. It fixes the scroll issue and the gap between last entry and bottom for all viewports. 
In addition the spec of fiori3 has bigger icons for the left nav.
Also please take a look to the font size and weight.

2021-02-25 14:48 UTC, JohannesDoberer approved these changes

2021-02-26 10:28 UTC, merged