Add release notes for v.1.13.0
SAP/luigi pull request #2078
Opened 2021-06-08 04:52 UTC by alexandra-simeonova

**Description**

Changes proposed in this pull request:

- Add release notes for Luigi v.1.13.0 to introduce the new changes in our blog 

**Related issue(s)**

2021-06-08 11:01 UTC, UlianaMunich commented on blog/2021-06-07-release-notes.md
> +Luigi 1.13.0 is the latest Luigi release. It includes updates of Fundamental Styles, new options in the user settings, as well as other features and bugfixes. Read the release notes below to learn mo
```suggestion
Luigi 1.13.0 is the latest Luigi release. It includes updates of Fundamental Library Styles, new options in the user settings, as well as other features and bug fixes. Read the release notes below to learn more.
```

2021-06-08 12:51 UTC, UlianaMunich commented on blog/2021-06-07-release-notes.md
> +#### Breaking changes in Fundamental Styles
```suggestion
#### Breaking changes in Fundamental Library Styles
```

2021-06-08 13:02 UTC, UlianaMunich commented on blog/2021-06-07-release-notes.md
> +In Luigi's [user settings](https://docs.luigi-project.io/docs/user-settings), an `enum` array can now can store options objects. You can use them if you want to add more options in the user settings
```suggestion
In Luigi's [user settings](https://docs.luigi-project.io/docs/user-settings), an `enum` array can now store options objects. You can use them if you want to add more options in the user settings for the user to choose from. These objects need `value` and `label` as key. For example:
```

2021-06-08 13:05 UTC, UlianaMunich approved these changes

2021-06-10 14:21 UTC, hardl requested changes
See my comment, rest looks good 👍

2021-06-10 14:21 UTC, hardl commented on blog/2021-06-07-release-notes.md
> +With Luigi v1.13.0, the new v0.17.0 of Fundamental Library Styles was included. It led to having breaking changes in the Luigi Dialog/Modal layout and Shellbar Counter. New HTML attributes were added
Maybe we could add sth. like
"As always this does only affect you if you have customized fundamentals css in your app" or sth. like that

2021-06-11 09:31 UTC, hardl approved these changes

2021-06-11 09:33 UTC, merged