Alert dismiss with key
SAP/luigi pull request #2162
Opened 2021-07-21 12:09 UTC by stanleychh

Origin draft PR #2135 

Fixes #2140

2021-07-28 08:16 UTC, alexandra-simeonova commented on client/luigi-client.d.ts
> +   * @param {Object} settings.links.LINK_KEY.dismissKey dismissKey which represents the key of link.
```suggestion
   * @param {Object} settings.links.LINK_KEY.dismissKey dismissKey which represents the key of the link.
```

2021-08-06 13:21 UTC, hardl requested changes
codewise looks good, but documentation is missing

2021-08-06 14:35 UTC, stanleychh commented
@hardl Thanks for your time for reviewing. I will add the documentation.

2021-08-12 08:43 UTC, hardl approved these changes
LGTM

2021-08-12 08:44 UTC, merged