Strip query params in linkmanager navigate
SAP/luigi pull request #2393
Opened 2021-11-23 19:30 UTC by JohannesDoberer

Fixes #2387

2021-12-09 13:17 UTC, hardl requested changes

2021-12-09 13:17 UTC, hardl commented on core/src/App.html
> +        if (e.source !== window && !e.data.params.intent) {
i guess it wouldn't harm to also check if e.data.params.link is truthy here

2021-12-15 08:57 UTC, stanleychh commented on core/src/App.html
> +        }
```suggestion
        const params = e.data.params;
        const { intent, link, newTab, modal, splitView, drawer, withoutSync } = params;
        if (e.source !== window && !intent && link) {
          link = link.split('?')[0];
        }
```

We repeated a lot of `e.data.params` here, as well as inside `luigi.navigation.open`.

2021-12-15 08:57 UTC, stanleychh commented on core/src/App.html
> +        }
We could declare `e.data.params` on the top and make the other conditions(newTab, drawer, splitView, etc...) shortly.

2021-12-16 11:02 UTC, stanleychh commented
Let's move this forward. 
The [luigi.navigation.open](https://github.com/SAP/luigi/blob/8ba179df2f5f81eb9cef812648b019504be6f85f/core/src/App.html#L1349) part needs further refactoring to reduce repetition in codebase. I will do that in a separate ticket then.

2021-12-16 11:02 UTC, stanleychh approved these changes

2021-12-17 09:19 UTC, merged