Add breadcrumbs documentation
SAP/luigi pull request #3202
Opened 2023-02-27 13:34 UTC by alexandra-simeonova

**Description**

Changes proposed in this pull request:

- Add breadcrumbs documentation

**Related issue(s)**
#2416

2023-03-09 13:44 UTC, ndricimrr reviewed
Some small comment to remove Typescript typings as this makes it harder to try out if copying it to Fiddle or a non-Typescript example

2023-03-09 13:44 UTC, ndricimrr commented on docs/navigation-advanced.md
> +                const label: string = item.label;
```suggestion
                const label = item.label;
```

2023-03-09 13:44 UTC, ndricimrr commented on docs/navigation-advanced.md
> +                  (itemCmp as any)._item = item;
```suggestion
                  itemCmp._item = item;
```

2023-03-09 13:44 UTC, ndricimrr commented on docs/navigation-advanced.md
> +                    'ui5-breadcrumbs-item',
```suggestion
                    'ui5-breadcrumbs-item'
```

2023-03-09 13:44 UTC, ndricimrr commented on docs/navigation-advanced.md
> +              ui5breadcrumbs.addEventListener('item-click', (event: any) => {
```suggestion
              ui5breadcrumbs.addEventListener('item-click', (event) => {
```

2023-03-09 14:44 UTC, ndricimrr commented on docs/navigation-advanced.md
> +Luigi allows you to add [breadcrumbs](https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Breadcrumb_Navigation) to your application. First, you need to create your own custom code imple
```suggestion
Luigi allows you to add [breadcrumbs](https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Breadcrumb_Navigation) to your application. You need to create your own custom code implementing breadcrumbs. Once the breadcrumbs config is set it is enabled by default for all nodes. If you wish to disable it for a particular node you need to set [showBreadcrumbs](navigation-parameters-reference.md#showbreadcrumbs): true for that node.
The breadcrumbs configuration structure looks like this:

      navigation.breadcrumbs = {
            omitRoot: false,  // if set to true, the root node in breadcrumb hierarchy is omitted 
            clearBeforeRender: true, // if set to true, the containerElement will be cleared first, before being rendered. If set to false, handling of the clear before render needs to be handled by your side 
            autoHide: true, // hide breadcrumbs when navigating to root node
            renderer: (containerElement, nodeItems, clickHandler)  => {
                  // containerElement - refers to HTML element that contains the breadcrumb structure to which you can append your own customised elements
                  // nodeItems : {
                       label: label of node,
                       node: navigation node,
                       route: node route,
                       pending: indicates whether node label has not been resolved yet or not
                  }
                  // clickHandler(node) , can be called per node, to navigate to that node
            }
      }


. In your custom code, you can choose any look and style for the breadcrumbs as well as define what should happen upon clicking them. However, the code should follow this general pattern and return the variable `breadcrumbs`: 
```

2023-03-09 14:48 UTC, ndricimrr commented on docs/navigation-advanced.md
> +var breadcrumbsConfig = {
```suggestion
navigation.breadcrumbs = {
```

2023-03-09 14:51 UTC, ndricimrr commented on docs/navigation-parameters-reference.md
> +- **description**: shows a breadcrumbs header for the node. See the [advanced navigation](navigation-advanced.md#breadcrumbs) document for more information.
if breadcrumbs configuration is setup, the breadcrumbs show for all nodes. This property allows disabling the breadcrumb for one particular node by setting it to `false` for that node.
```suggestion
- **description**: if breadcrumbs configuration is setup, the breadcrumbs show for all nodes. This property allows disabling the breadcrumb for one particular node by setting it to `false` for that node.. See the [advanced navigation](navigation-advanced.md#breadcrumbs) document for more information.
```

2023-03-09 14:52 UTC, ndricimrr commented on docs/navigation-parameters-reference.md
> +    showBreadcrumbs: true,
```suggestion
    showBreadcrumbs: false, 
```

2023-03-14 11:37 UTC, ndricimrr approved these changes
Looks good 👍

2023-03-14 14:36 UTC, JohannesDoberer commented
Blocked by #3198

2023-04-03 12:25 UTC, hardl requested changes

2023-04-03 12:25 UTC, hardl commented on docs/navigation-advanced.md
> +Below is another example which uses UI5 breadcrumbs:
... uses UI5 Web Components breadcrumbs:

2023-04-03 12:50 UTC, alexandra-simeonova commented on docs/navigation-advanced.md
> +Below is another example which uses UI5 breadcrumbs:
```suggestion
Below is another example which uses UI5 Web Components breadcrumbs: 
```

2023-04-03 13:16 UTC, hardl approved these changes

2023-04-04 06:40 UTC, merged