Write updated modal settings to url
SAP/luigi pull request #3339
Opened 2023-06-29 13:27 UTC by JohannesDoberer

Fixes #3338

2023-06-30 09:48 UTC, alexandra-simeonova commented on client/src/linkManager.js
> +   * Update current title and size of a modal. If `routing.showModalPathInUrl` is set to true, the URL will be updated with the modal settingds data.
```suggestion
   * Updates the current title and size of a modal. If `routing.showModalPathInUrl` is set to `true`, the URL will be updated with the modal settings data.
```

2023-06-30 09:48 UTC, alexandra-simeonova commented on client/src/linkManager.js
> +   * In addition you can specify if a new history entry wil lbe created with the updated URL.
```suggestion
   * In addition, you can specify if a new history entry will be created with the updated URL.
```

2023-06-30 13:08 UTC, hardl requested changes

2023-06-30 13:08 UTC, hardl commented on core/src/Modal.svelte
> +      elem.classList.remove('lui-modal-fullscreen');
why only remove in the else block?

2023-07-04 08:57 UTC, hardl approved these changes
LGTM

2023-07-07 09:55 UTC, merged