Documentation for container component
SAP/luigi pull request #3412
Opened 2023-08-23 11:19 UTC by alexandra-simeonova

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2023-09-20 13:02 UTC, JohannesDoberer approved these changes
LGTM

2023-09-25 08:48 UTC, hardl requested changes

2023-09-25 08:48 UTC, hardl commented on docs/getting-started.md
> +>**NOTE:** As of Luigi v2.5, you can use [Luigi Container](luigi-container.md) to embed a Luigi micro frontend into any existing application without the need of it being a Luigi Core app.
Luigi container is detached from core/client versioning and follows it's own release cycle

2023-09-25 08:48 UTC, hardl commented on docs/luigi-container.md
> +1. You can find a Luigi Container example on [GitHub](https://github.com/SAP/luigi/tree/main/container). First, first clone the Luigi repository if you haven't already done so:
redundant "first" ;)

2023-10-31 18:40 UTC, hardl approved these changes
LGTM!

2023-10-31 19:23 UTC, merged