client-support-angular: add fromVirtualTreeRoot 'truncate' option to docu
SAP/luigi pull request #3537
Opened 2023-11-21 12:02 UTC by alexandra-simeonova

**Description**

Changes proposed in this pull request:

- Adds the `truncate` option to the documentation for Angular Support Library.

**Related issue(s)**
Fixes #3535

2023-11-22 08:29 UTC, JohannesDoberer approved these changes

2023-11-22 11:39 UTC, hardl requested changes

2023-11-22 11:39 UTC, hardl commented on client-frameworks-support/client-support-angular/projects/client-support-angular/README.md
> +{path: 'luigi-client-support-preload',component: Sample1Component,data: { fromVirtualTreeRoot: : {"truncate": "*/projects"} }}
maybe a second example without the asterisk would be good, also for the following occurences

2023-11-23 16:16 UTC, hardl approved these changes
LGTM

2023-11-24 10:22 UTC, merged