added release notes for 2.12 and 2.13
SAP/luigi pull request #3752
Opened 2024-05-24 14:45 UTC by smahati

**Description**

Changes proposed in this pull request:

- Release notes for 2.12 and 2.13

**Related issue(s)**

2024-05-27 07:28 UTC, JohannesDoberer commented on blog/2024-05-23-release-notes.md
> +The Left Nav bar is now accessible when in BTP Layout.
@smahati
The change is that when the BTP layout is active, the left nav is accessible from the keyboard.

2024-05-31 09:58 UTC, JohannesDoberer commented on blog/2024-05-03-release-notes.md
> +This addition lets you update the context values for visible iframes and LUI web components.
```suggestion
This addition lets you update the context values for visible iframes and Luigi web components.
```

2024-05-31 10:03 UTC, JohannesDoberer commented on blog/2024-05-03-release-notes.md
> +If you have implemented your own `page not found` error handler function, then you can set **ignoreLuigiErrorHandling** to `true` in your routing configuration.
```suggestion
If you have implemented your own `page not found` error handler function, then you can set [**ignoreLuigiErrorHandling**](https://docs.luigi-project.io/docs/navigation-parameters-reference?section=pagenotfoundhandler) to `true` in your routing configuration.
```

2024-06-06 10:03 UTC, JohannesDoberer approved these changes

2024-06-06 12:38 UTC, hardl requested changes

2024-06-06 12:38 UTC, hardl commented on blog/2024-05-03-release-notes.md
> +#### Change Luigi Core Version on the Fly in Luigi Fiddle
this is a feature in luigi-fiddle, not luigi itself, so should not be part of the luigi release notes

2024-06-13 12:07 UTC, hardl approved these changes

2024-06-13 12:08 UTC, merged